config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'posts#index'

  resources :posts do
    member do
      post :save
    end
  end
  resources :categories
  resources :comments, only: [:create, :new]
end

app/models/post.rb
class Post < ActiveRecord::Base
  acts_as_commentable

  validates :title, length: { maximum: 255 }, presence: true
  validates :link, presence: true, if: :link?
  validates :link, length: { maximum: 2000 }
  validates :body, presence: true, if: :text?
  validates :category_id, presence: true
  enum post_type: [:link, :text]

  belongs_to :category
  belongs_to :user
  default_scope { order('updated_at DESC') }
  scope :with_categories, -> { includes(:category) }
  scope :with_user,       -> { includes(:user)     }

  self.per_page = 5
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :find_post, only: [:show, :edit, :update, :destroy, :save]
  before_action :authenticate_user!, only: [:new, :create, :edit, :update, :destroy]

  def index
    @posts = Post.with_categories.with_user.includes(:comment_threads).page(params[:page])
  end

  def show
    @comment = Comment.build_from @post, current_user.id, ''
  end

  def edit
  end

  def new
    @post = Post.new
    @post.post_type = params[:post_type] if params[:post_type].present?
  end

  def create
    @post = Post.new post_params
    @post.user_id = current_user.id
    if @post.save
      redirect_to posts_path, flash: { notice: 'It worked' }
    else
      flash.now[:error] = @post.errors.full_messages
      render :new
    end
  end

  def save
    ElevenNote.create_from @post, current_user.elevennote_api_key
    redirect_to @post, notice: 'Saved to ElevenNote!'
  rescue
    redirect_to @post, alert: 'We were unable to save that to ElevenNote.'
  end

  def update
    if @post.update post_params
      redirect_to post_path(@post), flash: { notice: 'Updated!' }
    else
      flash.now[:error] = @post.errors.full_messages
      render :edit
    end
  end

  def destroy
    if @post.destroy
      redirect_to posts_path, flash: { notice: 'Your post has been removed.' }
    else
      redirect_to posts_path, flash: { notice: 'We were unable to remove that post.' }
    end
  end

  private

  def post_params
    params.require(:post).permit(:title, :link, :body, :post_type, :category_id)
  end

  def find_post
    @post = Post.find params[:id]
  end

end

app/views/posts/_actions.html.erb
<% if user_signed_in? -%>
  <ul class="actions">
    <li><%= link_to comment_link_text(post.comment_threads.length), post_path(post, anchor: 'comments') %></li>
    <li><%= link_to 'edit', edit_post_path(post) %></li>
    <li>
      <%= link_to 'delete', post_path(post), method: :delete, data: { confirm: 'Are you sure? This cannot be undone.' } %>
    </li>
    <li>
      <% if current_user.elevennote_api_key.present? %>
        <%= link_to 'save', save_post_path(post), method: :post %>
      <% else %>
        <%= link_to 'add your elevennote api key to save', edit_user_registration_path(current_user) %>
      <% end %>
    </li>
  </ul>
<% end -%>

app/views/posts/_form.html.erb
<%= form_for @post do |f| %>

  <!-- Do not allow the title to be edited -->
  <% if f.object.new_record? %>
    <fieldset>
      <%= f.label :title %>
      <%= f.text_field :title %>
    </fieldset>
  <% end %>

  <fieldset>
    <% if f.object.link? %>
      <%= f.label :link %>
      <%= f.text_field :link %>
    <% elsif f.object.text? %>
      <%= f.label :body %>
      <%= f.text_area :body %>
    <% end %>
  </fieldset>

  <fieldset>
    <%= f.label :category_id %><br>
    <%= f.collection_select :category_id, Category.all, :id, :name, prompt: 'Select a category' %>
  </fieldset>

  <%= f.hidden_field :post_type %>
  <%= f.submit class: 'btn btn-default' %>
<% end %>

app/views/posts/_list.html.erb
<ul class="posts">
<% posts.each do |post| %>
  <li>
    <%= render 'posts/slug', post: post %>
    <%= render 'posts/actions', post: post %>
  </li>
<% end %>
</ul>
<%= will_paginate posts %>

app/views/posts/_slug.html.erb
<%= post_title_link(post) %>
<div class="tagline" title="<%= post.created_at %>">
  submitted <%= time_ago_in_words post.created_at %> ago
  to <%= link_to post.category.name, category_path(post.category) %>
  <%= "by #{post.user.username}" if post.user.present? %>
</div>

app/views/posts/edit.html.erb
<%= render 'form' %>

app/views/posts/index.html.erb
<%= render 'list', posts: @posts %>

app/views/posts/new.html.erb
<%= form_for @post do |f| %>
  <fieldset>
    <%= f.label :title %>
    <%= f.text_field :title %>
  </fieldset>

  <fieldset>
    <% if f.object.link? %>
      <%= f.label :link %>
      <%= f.text_field :link %>
    <% elsif f.object.text? %>
      <%= f.label :body %>
      <%= f.text_area :body %>
    <% end %>
  </fieldset>

  <%= f.hidden_field :post_type %>
  <%= f.submit class: 'btn btn-default' %>
<% end %>

app/views/posts/show.html.erb
<article class="post">
  <%= render 'slug', post: @post %>
  <% if @post.text? -%>
    <section class="body"><%= @post.body %></section>
  <% end -%>
  <%= render 'actions', post: @post %>

  <%= render 'comments/form', comment: @comment %>


  <%= nested_ol @post.comment_threads, id: 'comments' do |comment| %>
    <div class="tagline" title="<%= comment.created_at %>">
      <%= comment.user.username %>
      <%= time_ago_in_words comment.created_at %> ago
    </div>

    <section class="body">
      <%= comment.body %>
    </section>

    <ul class="actions">
      <li><%= link_to 'reply', new_comment_path(parent_id: comment.id, format: 'js'), remote: true, method: :get %></li>
    </ul>

    <div id="reply-form-<%= comment.id %>" style="display: none"></div>
 <% end -%>


</article>